### ISSUE TITLE
In "Tools" page the 'Pump flow rate' should be renamed to 'Station flow rate'

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#100]
In "Tools" page the 'Pump flow rate' should be renamed to 'Station flow rate'.
In Greek the translation is: Παροχή ζώνης

**Comment by kickapoo** [comment]
Greek translation will be again along with a global translation commit

**Comment by nmalamos** [comment]
There is another 'pump' that needs replacing.
The last tool.
