### ISSUE TITLE
Specify OpenLayers version

### ISSUE THREAD

**Issue by aptiko** [openmeteo/aira#101]
It gets "http://openlayers.org/api/OpenLayers.js", it would be better if it specified a version.

**Comment by aptiko** [comment]
//cdnjs.cloudflare.com/ajax/libs/openlayers/2.13.1/OpenLayers.js would be better.

**Comment by aptiko** [comment]
By the way, it is not a good idea to use many CDNs. Since we are already using cloudflare, let's stick to cloudflare if there's no reason to add another. So angular should be read from //cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.min.js. We also get a css and two images from openlayers.org (without specifying version); I don't know if cloudflare serves these as well.

**Comment by kickapoo** [comment]
Couldn's find in https://cdnjs.com/,  any link about `OpenStreetMap.js`.  
If the current link is ok with you (@aptiko) , please close issue.
