### ISSUE TITLE
Drawing rasters in OpenLayers is too slow

### ISSUE THREAD

**Issue by aptiko** [openmeteo/aira#109]
Apparently it takes 4 seconds for mapserver to read the 4000-layer mapfile.

**Comment by aptiko** [comment]
Here's what the [mapserver documentation](http://mapserver.org/optimization/mapfile.html#layers) says:
> If you have a complex application, consider using multiple simple and specific Map Files in place of one large ‘do everything’ Map File.

This means we should create one mapfile for each variable.

Another way it might speed up greatly (but I'm not certain about that) is to not run mapserver anew in each request, but run it persistently between requests. I'm not certain how apache is handling it at the moment, but I think it starts it on every request.

**Comment by nmalamos** [comment]
I think that the implementation of the first solution does not exclude the second.
We can create one mapfile for each variable and afterwards we are looking about the second solution.

Also, I found this: http://simonmercier.net/blog/?p=37, that has several interesting tips
