### ISSUE TITLE
Uses outdated lists of files

### ISSUE THREAD

**Issue by aptiko** [openmeteo/aira#24]
In `aira/irma/config_data` some variables are defined as `glob`s. These globs are evaluated only once, i.e. when execution starts, or when the first request after aira is started is made; they should be evaluated in each request.

**Comment by kickapoo** [comment]
I cant understand the issue. 
`aira/irma/main` imports in each request 
``` python 
from aira.irma.config_data import PRECIP_DAILY as d_rain_fps 
etc```

doesn't this import ensures `aira/irma/config_data`  `glob` evaluation ?

**Comment by kickapoo** [comment]
Trying to understand the issue,  maybe a `middleware` class will do the trick? 

For example: 

```python
class CacheDatasetFilePaths(object):
    def process_request(self, request):
         # Load aira.irma.config_data.py 
        return responce
````
