### ISSUE TITLE
Zoom in "update_agrifield" openlayers map

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#28]
In "update_agrifield" page, the map zoom should be accordingly set so the scale of the map is initially at 200 meters. It is awkward for the user to zoom every time in order to see his/her field.

**Comment by kickapoo** [comment]
Until issue #29  is resolved, 'zoom in' is set to maximum value that don't cause any display problems ( commit `#70d981f7 - Update default zoom in map`)
