### ISSUE TITLE
Maximum zoom in openlayers maps

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#29]
To my knowledge, the WMS server of the Hellenic Cadastre provides zoom for scales up to 10 meters, so the maximum zoom should be at least 50 meters.

**Comment by kickapoo** [comment]
In `aira-maps`, all the parameters are set to allow Hellenic Cadastre WMS server to `zoom in` to the maximum default value.   Do you have any link or resource about this WMS server?

**Comment by nmalamos** [comment]
From what I remember it has to do with the Openlayers variable: numZoomLevels and not with the associated WMS service.
You can see here: http://trac.osgeo.org/openlayers/wiki/SettingZoomLevels

**Comment by kickapoo** [comment]
I have already tried to change those variables with no result.

**Comment by nmalamos** [comment]
Obviously this has to do with the fact that I am not familiar with OL3 (OpenLayers 3) but with OL2 as seen here: http://geo.teimes.gr/web/apps/apps1/ (second map)
The WMS service is here: http://gis.ktimanet.gr/wms/ktbasemap/default.aspx
and provides scales up to: 1:1.953125 (very large scale)
Maybe here: http://openlayers.org/en/v3.4.0/apidoc/ol.View.html
you can find something useful.

**Comment by nmalamos** [comment]
Please refer to: http://dev.openlayers.org/releases/OpenLayers-2.13.1/examples/zoomLevels.html
I think that zoom is should not be defined inside "var ktimatologio"

**Comment by kickapoo** [comment]
Maximum zoom in openlayers maps is corrected to all maps except `index` (welcome page) as in `index` page map has the spatial representation of datasets.
