### ISSUE TITLE
Add the option of automatically registering irrigations using an automated hydrometer

### ISSUE THREAD

**Issue by aptiko** [openmeteo/aira#297]
Our associate Christos Koliopanos has created a flowmeter that uploads data to [The Things Network](https://www.thethingsnetwork.org/). We call that "the Koliopanos flowmeter", or, officially, the LoRA_ARTA flowmeter.

To the three options for specifying irrigations we will add a fourth one: "I have a telemetric flowmeter". When this is selected, the following three fields should appear:
* **Type of telemetric system**. This will be, say, a drop down, currently having only one option: `LoRA_ARTA`
* **System code**. This will be something like `045#34TT`. I don't know what it is. A password? An id?
* **Percentage of water that corresponds to this field (%)**. We already have that in the flowmeter readings option.

Your mission Abdullah, should you choose to accept it. is to implement all that. You will start by creating an account at The Things Network and give us your account name so that we add you as collaborator to the appropriate application. Then you will receive further instructions.

[This message will self-destruct in five seconds.
](https://www.youtube.com/watch?v=qDsfou6UfjU)

Good luck Abdullah!

**Comment by aptiko** [comment]
OK, what we've been calling a "hydrometer" is actually called a flowmeter. A hydrometer is something different. To make it more confusing, the Greek word υδρόμετρο means a flowmeter, not a hydrometer. I changed everything in the code, and I also changed it in the description of this issue.

**Comment by AbdullahKady** [comment]
Lindsey is awesome! I was anticipating a rick-roll to be honest :grin:

As for the task, sure thing, will get to it. I have been quite busy for the past week so I didn't see it till now.
I'm assuming after the creation it will be an automated process of reporting; either web-hooks or cron tasks from the network that I'll be registering to?

Anyway, will create the account and let you know soon.

**Comment by aptiko** [comment]
We don't know yet. If The Things Network can push data upon receiving it from a flowmeter, we'll consider this option. Otherwise cron or celerybeat.

BTW, I think I've been wrong in the description about adding a fourth option. Probably the "receive irrigations automatically" option should be elsewhere, and it should be adding irrigations (which I guess should then be editable/deletable).

**Comment by aptiko** [comment]
You have been given access to the "IrmaFlowMeter" application in The Things Network (TTN) (Console, Applications). You should be able to view the data (in the "Data" tab).

There are two ways to get the data ("Integrations" tab): 1) HTTP; 2) Data storage. We will use data storage.

The HTTP integration pushes data from TTN to a listener (e.g. aira) using POST. For the data storage integration, you pull the data from TTN (using HTTP GET I believe). The problem with the HTTP integration is that as soon as the flowmeter uploads some data, that data is POSTed with the HTTP integration. As far as Christos told me, if something goes wrong, it won't post that data again. This will result in some data missing, and in this application we need the full history of the data.

The data storage, on the other hand, keeps data for the last seven days or something. We only need to get all data we don't already have and enter it to the database. We can use either a management command or a celery task. We have a script that runs every 24 hours: it fetches all the data it needs, performs aggregation, spatial integration and calculation of evaporation, and initiates a re-calculation of all agrifields. We'll simply tell this script to also execute the fetching of data from TTN. If it's done asynchronously with Celery, we need to make sure that the fetching of data from TTN completes before the agrifields start to be calculated.

The flowmeter measurements are given by the `SensorFrequency` variable. The units is something like pulses per second or minute. The thing is that if you divide `SensorFrequency` by 6.8, you get litres per minute.

**Comment by aptiko** [comment]
BTW, I just merged a large refactoring of the JS. Rebase before continuing.
