### ISSUE TITLE
Custom kc default value

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#35]
In the custom kc field the default value taken from the crop data should appear, in order to provide guidance to the users.

**Comment by kickapoo** [comment]
This issue (along with the others duplicates) is partial fixed in the following commits:  kickapoo@217088f3ed35eba20b196ecd4d8e2cc1a1f9acc2, kickapoo@67063eb84490c73f0221b4857eb548ef8d26234f, kickapoo@8a0e01c14a23ee1e89631949fdcb427c043865ea.
