### ISSUE TITLE
Add monthly evapotranspiration (mm) in "View historical available data"

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#40]
The system should provide information about monthly evapotranspiration (mm) and mean monthly evapotranspiration (mm/d) in "View historical available data", that are produced by aggregation of the daily values of each month.
The system should maintain for every year, 12 rasters (one for each month) for monthly evapotranspiration (mm) and 12 rasters (one for each month) for mean monthly evapotranspiration (mm/d). This is valuable information to the users.
Those  rasters should be available for downloading from the WCS service of the system.

**Comment by nmalamos** [comment]
Calculate only monthly evapotranspiration (mm)

**Comment by aptiko** [comment]
I need @kickapoo's opinion on the UI here. The UI is made to select a day, not a month. How do you propose to do it?

**Comment by kickapoo** [comment]
I am thinking a `button-switch`where user can switch between daily and montly selection.

Switch will handle if a daily or monthly dropdown/calendar will be shown to user.

**Comment by nmalamos** [comment]
Maybe we should leave it as is and when the user changes month, then the map will show the chosen month's ET0.
For the current month we will show the sum of ET0 values up to the last day of historical data.

**Comment by aptiko** [comment]
I have made mapserver serve the monthly evapotranspirations at http://arta.irrigation-management.eu/mapserver/historical/monthly/. The layer names are like `Monthly_evaporation_2015_08`. I leave it to you to fix the UI for that.

**Comment by kickapoo** [comment]
Please change layer names to `Monthly_evaporation_2015-08`. 
 This will help me to keep constant url assembles and will follow our previous daily example,  `Daily_rain_2015-09-10`

**Comment by kickapoo** [comment]
@aptiko 
I having trouble with the mapserver url and layer call. 
Please see my push branch issue40 (`/kickapoo/aira/tree/issue40`).

Run the development server and open  developer tools. Your will see at console log the output of `url_call` and `layers_call` variables.
Switch to monthly view and select a month.  You will see no raster is fetched but `url_call` and 'layer_call` are the same as your previous comment. 

Also, it not clear to me, we  want to add only `monthly_evaporation`? not all meteorological variables?

**Comment by aptiko** [comment]
I think the problem is that you are using `Monthly_evaporation_2015_08`, but the correct is `Monthly_evaporation_2015-08`, with a hyphen. (It was like this from the beginning, I wrote it incorrectly in a comment above).
