### ISSUE TITLE
"update_agrifield" custom Kc field value

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#41]
There is a "23" placed in the custom Kc field value. In order to be consistent with the other fields the value should be set to: "Kc"

**Comment by kickapoo** [comment]
Please provide more details. Its not clear to me. I think you referring to
try-demo user value to be changed?

**Comment by nmalamos** [comment]
I mean this:
![screenshot 2015-04-12 21 45 40](https://cloud.githubusercontent.com/assets/11832693/7107001/48bdc956-e15d-11e4-9f08-309adff1bc6a.png)

**Comment by kickapoo** [comment]
This value exists in `Try` mode and can be changed any time. Please remember that `Try` mode is just a `demo` user logged in to system. Anyone can add/change/delete agrifield or values.

**Comment by nmalamos** [comment]
This screenshot is from my account: nmalamos, Field: "MyField1".
Nevertheless, Kc = 23 makes no sense since it is totally out of range.
Kc ranges from 0.1 - 1.5, I am preparing the list right now.
