### ISSUE TITLE
"Irrigation Advice" not showing in "home" and in "advice"

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#42]
The irrigation advice should be set to:
<b>Irrigation advice:</b>
According to the available information, from <i>"initial irrigation date and time"</i> onwards you need to apply at least <i>"Irrigation Water Amount"</i> mm of irrigation water.

After that, add Ks to the existing table, in order for the user to see the existence or not of plant stress.

![screenshot 2015-04-13 14 28 19](https://cloud.githubusercontent.com/assets/11832693/7114776/5c05a02e-e1e9-11e4-8bfe-b7504e0115b8.png)

Initial irrigation:
![screenshot 2015-04-13 15 07 48](https://cloud.githubusercontent.com/assets/11832693/7115212/f0a0a350-e1ee-11e4-83c2-e030134bc6c0.png)

**Comment by kickapoo** [comment]
Please i am bit confused with `Ks`, i can find any information about it.

**Comment by nmalamos** [comment]
Ks is this:
https://github.com/openmeteo/pthelma/blob/master/pthelma/swb.py#L150
