### ISSUE TITLE
Custom parameters groups

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#49]
From top to bottom following the position of appearing.

1st group:
Title: Irrigation Management / Διαχείριση Άρδευσης
Contents: Irrigation efficiency, Irrigation Optimizer

2nd group:
Title: Crop / Καλλιέργεια
Contents: Kc, Maximum allowable depletion, Root depth (max), Root depth (min)

3rd group:
Title: Soil /  Έδαφος
Contents: Field Capacity, Permanent Wilting Point, Soil moisture at saturation

**Comment by kickapoo** [comment]
closed from kickapoo@34ef77152fad6192e9fcba0ee791f29c734305b9
