### ISSUE TITLE
Set Inet_i=0 in theta_calc (swb.py#L71) in "advice" page

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#50]
In "advice" page Inet_i should be set equal to 0 in theta calculation, in order for the theta to decrease. Otherwise, theta remains stable at Field Capacity (or other theta, depending on the Irrigation Optimizer setting).
https://github.com/openmeteo/pthelma/blob/master/pthelma/swb.py#L71

**Comment by kickapoo** [comment]
Waiting for pthelma pull request https://github.com/openmeteo/pthelma/pull/25 to be accepted in order to close this issue.
