### ISSUE TITLE
Icons in "home" page

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#56]
The following icons should be placed accordingly in front of each field's irrigation advice in the "home" page.
The Cool.png to the fields that do not require irrigation, whether the Watchout.png to the fields that require irrigation.
![cool](https://cloud.githubusercontent.com/assets/11832693/7181708/57c56ecc-e455-11e4-8fa9-5c156d9872e2.png)
![watchout](https://cloud.githubusercontent.com/assets/11832693/7181712/5d31c374-e455-11e4-9f4c-e11c0b3f7f85.png)

**Comment by kickapoo** [comment]
Sample preview
![screenshot 2015-04-16 20 35 30](https://cloud.githubusercontent.com/assets/5064612/7187282/26862810-e478-11e4-894b-460dd2c693c8.png)
