### ISSUE TITLE
The background image of IRMA system templates (openmeteo/aira-irma), should match the Enhydris background 

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#61]
The background image of IRMA system pages, should match the Enhydris background image (clouds....)

**Comment by kickapoo** [comment]
You really want IRMA systems to look like this (preview 67% browser zoom) ? 
![screenshot 2015-04-17 13 21 14](https://cloud.githubusercontent.com/assets/5064612/7200353/cca9ef88-e504-11e4-93b4-8436f0de402b.png)

If yes, please provide me for header and footer transparent images (iam referring to IRMA project images).

**Comment by nmalamos** [comment]
Proceed as mentioned above. It is OK, with Tsirogiannis.
Also, send Tsirogiannis the Enhydris background image.

**Comment by kickapoo** [comment]
Templates are updated through  kickapoo@1cdca02883afc953256e301627a940f99e5cb0f3 commit in `openmeteo/aira-irma` templates.

**Comment by nmalamos** [comment]
I am very sorry to announce that Tsirogiannis changed his mind.
We should keep the white background.
So please revert to the previous version.
Also, use this logo:
![irmawebsitelogo](https://cloud.githubusercontent.com/assets/11832693/7220749/abb165f8-e6db-11e4-9d10-25540da6b763.png)

**Comment by kickapoo** [comment]
fixed using aira-irma@12a95641565e9d8b675e3f8e37b17ca9b78eaf2b
