### ISSUE TITLE
Different Ks and Irrigation Water Amount in "home" and "advice" pages for the same field and the same timestamp

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#64]
Different Ks and Irrigation Water Amount in "home" and "advice" pages for the same field and the same timestamp (17/04/2015 12:00:00).
The Irrigation Water Amount fits to the: <i>17/04/2015 00:00</i> timestamp, while Ks should be in every case smaller than 1.0
Also, according to the "advice" page, irrigation should take place at  <i>17/04/2015 00:00</i> and not at  <i>17/04/2015 12:00:00</i>
My opinion is that the "advice" is right and the "home" is wrong....
![screenshot 2015-04-18 15 22 01](https://cloud.githubusercontent.com/assets/11832693/7215398/bd23bd70-e5de-11e4-95d7-2221248e65c4.png)

![screenshot 2015-04-18 15 22 12](https://cloud.githubusercontent.com/assets/11832693/7215400/c97d5a90-e5de-11e4-8696-8fcf7f624680.png)

**Comment by nmalamos** [comment]
This is not happening for  Irrigation Water Amount in this other field, while Ks is still different (1.0 instead of 0.99):
![screenshot 2015-04-18 15 30 50](https://cloud.githubusercontent.com/assets/11832693/7215425/fe969da8-e5df-11e4-84bb-ae677885f6af.png)

![screenshot 2015-04-18 15 30 44](https://cloud.githubusercontent.com/assets/11832693/7215428/061ddfa0-e5e0-11e4-9293-470afdb9aa17.png)

**Comment by kickapoo** [comment]
From my understanding about model structure and `aira` model calls , this behaviour may be consider valid as in `home` view `aira` runs forecast data with `Inet_in="YES"` and in `advice` page runs forecast data with `Inet_in="NO"`. 
This difference means that we have 2 different model structures running in the same field using the same parameters, so the results will differ in some extent.  

Recapping `aira` calls in `irrigation event` case:
1. Find latest user irrigation time log
2. Calculate `theta_init`, `Dr0` based on initial condition & if `applied water` is provided
3. Get `Dri_historical` by running historical data with step (2) parameters, `Inet_in="NO`.
4. Use step(4) `Dr_i`  and run model with forecast data:
     i) in `Home` page `Inet_in="YES"`
    ii) in `Advise` page `Inet_in="NO"`

`Home` page table is the result of searching in models run report where `Irrigate==1`
`Advise` page table is the hole report from model run.

**Comment by nmalamos** [comment]
OK, understood.
Then some changes should be made in the irrigation events that appear in "Show/Hide" table at "home" page.
I will open a new one with the description of these changes.
