### ISSUE TITLE
Change units of evapotranspiration in "View historical available data" to W/m²

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#67]
Change units of evapotranspiration in "View historical available data" to W/m² instead of Mj/m2/h.
Since today I realized that the Mapserver provides evapotranspiration maps in  W/m²

**Comment by kickapoo** [comment]
fixed both in openmeteo/aira@247749f920ddc735759efa57dbf87731a8aa471b and aira-irma@9ef90cc02c97fc0e94223de16cf9ecef5a7dfc6c

**Comment by nmalamos** [comment]
My mistake.I was referring to Solar Radiation.
Obviously I am too sick...
