### ISSUE TITLE
The "Irrigation Advice" in "home" page should include the "Ifinal" from historical data

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#69]
The "Irrigation Advice" in "home" page should include the "Ifinal" mm from historical data, even if Ifinal=0, like this:
...............
Irrigation Advice:
<b> Since the last recorded irrigation (<i>irr_date</i>) up to <i>last_historical data_date</i>, <i>Ifinal</i> mm of additional water are needed. </b>
Based on the available information, from 17/04/2015 to 19/04/2015, irrigation should be applied according to the following table:
..........
EL:
...........
Συμβουλή Άρδευσης:
<b> Από την τελευταία καταχωρημένη άρδευση (<i>irr_date</i>) ως και <i>last_historical data_date</i>, απαιτούνται <i>Ifinal</i> mm επιπλέον νερό. </b>
Βάσει των διαθέσιμων δεδομένων, από 17/04/2015 έως 19/04/2015, η άρδευση μπορεί να πραγματοποιηθεί σύμφωνα με τον ακόλουθο πίνακα:

**Comment by kickapoo** [comment]
I closed the issue but please see the attached screenshot with the greek translation.  I  made minor change to help me with the translation tags.
If my minor change is a problem, please reopen the issue. 

![screenshot 2015-04-23 13 53 59](https://cloud.githubusercontent.com/assets/5064612/7295625/96589086-e9c0-11e4-9e4b-067d8e36976c.png)

**Comment by nmalamos** [comment]
The dates should follow the format appearing in the second line, e.g. 08/04/2015 
Not like this: April 8, 2015
Also, only the date should appear, <b>not the time</b>

**Comment by nmalamos** [comment]
With the updated date format (in parentheses), do it like this:
...............
Irrigation Advice:
Since the last recorded irrigation <b>(</b><i>08/04/2015</i><b>)</b> up to <i>12/04/2015</i>, there is need of <i>Ifinal</i> mm additional water. 
Based on the available information, from 17/04/2015 to 19/04/2015, irrigation should be applied according to the following table:
..........
EL:
...........
Συμβουλή Άρδευσης:
Από την τελευταία καταχωρημένη άρδευση <b>(</b><i>08/04/2015</i><b>)</b> ως και <i>12/04/2015</i>, υπάρχει ανάγκη <i>Ifinal</i> mm επιπλέον νερού. 
Βάσει των διαθέσιμων δεδομένων, από 17/04/2015 έως 19/04/2015, η άρδευση μπορεί να πραγματοποιηθεί σύμφωνα με τον ακόλουθο πίνακα:
