### ISSUE TITLE
EN to EL translations of crop types and irrigation systems

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#70]
The provided translations of crop types and irrigation systems into Greek, should be implemented like this:
EL_name (EN_name)

**Comment by kickapoo** [comment]
I am facing an `encoding` problem in the model instance reference with greek polytonic language 
For example in `IrrigationType` model there is the classic reference:

```python 
def __unicode__(self):
        return u"{}".format(str(self.name))
```
and the error  in admin and user page is :
`'ascii' codec can't encode characters in position 0-6: ordinal not in range(128)` 

I am stack with ideas how to solve this... Anything that i tried is leading me to the same error

**Comment by nmalamos** [comment]
Mac csv send, with transalations

**Comment by kickapoo** [comment]
@nmalamos , thank about that.

**Comment by kickapoo** [comment]
For future reference to any django-user that might came across from random search to our issue. 
I manage to fix the greek language model instance reference by changing `return u"{}".format(str(self.name))` to `return unicode(self.name)`
