### ISSUE TITLE
Use the right IRMAwebsiteLogo.png

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#74]
The right logo should be applied.
Please replace current with: IRMAwebsiteLogo.png

![irmawebsitelogo](https://cloud.githubusercontent.com/assets/11832693/7442770/ebbe2c66-f127-11e4-88d9-fd66aff3027d.png)

**Comment by kickapoo** [comment]
In which you are referring? The current img is with the transparent
background  that was sent during the issue of using openmeteo background
pic.

**Comment by nmalamos** [comment]
Tsiroyiannis provided two versions of the logo.
Obviously this caused a mix up and the one used was not the right one.
He mentioned that the logo should be changed to the above.

**Comment by kickapoo** [comment]
This issue is referring to the special templates files for aira-irma (repository https://github.com/openmeteo/aira-irma)
Commit: aira-irma@5dd11e524b6ad8ef71bdaf34e319a33c673a4702
