### ISSUE TITLE
In "create_irrigationlog", List of Irrigation Events should show: Applied water (m3) in case of Applied Irrigation Water (m3) = None

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#76]
In `create_irrigationlog`, List of Irrigation Events should show how many m3 of water the system assumes that were applied water in case of `Applied Irrigation Water (m3)` = `None`.
The calculation is demonstrated in IRMA_DW_Balance3.xlsx or IRMA_DW_Balance3_1.xlsx in the sheet: "Initial conditions" Case 2, ln. 18, cell: V18

The output should be:
 `Applied Irrigation Water (m3)` 
`None` (`Calculated Applied Irrigation Water `)
This message should follow exactly below the record:
*Irrigation water is estimated using system's default parameters.*
EL:
*Η Δόση άρδευσης βασίζεται στο προκαθορισμένο σύνολο δεδομένων.*

**Comment by kickapoo** [comment]
I think you have confused the purpose of  `List of Irrigation Events`. This list show only user Irrigation log database, like a small record calendar for easy management and update of Applied Water  values.

The functionality you suggest can be implemented  in the cases of `home` or `advice` where initial conditions are estimated through `pthlema.swb` model calculation.

**Comment by kickapoo** [comment]
So,  i will make it in the `advice` page.

**Comment by aptiko** [comment]
The superscripts ² and ³ are Unicode characters 0x00b2 and 0x00b3. In X11 you can get them, for example, with <Ctrl+Shift+u> b2 <ENTER>. If your operating system does not have such a facility, you can copy and paste them from this comment.

**Comment by kickapoo** [comment]
@aptiko ty for that, i will bookmark this issue!!!

**Comment by aptiko** [comment]
If you liked it that much, here is my complete personal reference. Whenever you encounter a symbol that is not there, you can often find it in Wikipedia. For example, I searched the web for "o with slash" and the first result was https://en.wikipedia.org/wiki/%C3%98. You then search the page for "unicode" and you have it (or you copy-paste the symbol from the page).

    é 00e9
    è 00e8
    ê 00ea
    ç 00e7
    Ö ö d6 f6
    – (en dash) 2013
    — (em dash) 2014
    “ (opening quote) 201c
    ” (closing quote) 201d
    ° 00b0
    € 20ac
    « 00ab
    » 00bb
    ⁰ 2070
    ¹ 00b9
    ² 00b2; ³ 00b3
    ⁴ 2074; ⁵ 2075; ... ⁹ 2079
    ₀ 2080; ₁ 2081; ... ₉ 2089
    × 00d7
    ≤ 2264
    ≥ 2265
    ‰ 2030
    ± 00b1
    · (ano teleia) 00b7
