### ISSUE TITLE
In "create_irrigationlog", List of Irrigation Events in Greek shows twice the units (m3)

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#77]
In "create_irrigationlog", List of Irrigation Events in Greek shows twice the units (m3):

Δόση άρδευσης (m3) (m3)

Keep the cubic meters with the superscript `3`

**Comment by kickapoo** [comment]
This issue  involves both `openmeteo/aira-irma` templates for IRMA project and the core `aira` code.

Commits:
`openmeteo/aira`: kickapoo@af999018d1a653459e145708a6e7780bd24888fc
`openmeteo/aira-irma`: kickapoo@d8dc33cb3f4acf1eb322f662682b80ceb9a9b11d
