### ISSUE TITLE
Email notifications to users

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#79]
Following my email of 04/05/2015 12:46 and the skype conversation between myself, `aptiko` and Tsirogiannis, the email notifications tool should be implemented accordingly.
The only addition to the mentioned specs is that the default value of the dropdown menu should be set to: `none`, meaning that the email notifications tool will not send emails to the users, by default.

**Comment by kickapoo** [comment]
@nmalamos , it would be nice to have a small description of the suggested feature that need to be done, just for history of the issue. 

@aptiko, should i start by adding the button to the template? just for the front-end without any functionality?

**Comment by nmalamos** [comment]
In the `Account` page, under the *Notification setup* group, the system should provide the option for the user to choose when to receive e-mails with information about the state of his fields (`Home`) with links to http://arta.irrigation-management.eu/, for more information.
The user should have the following options, through a dropdown menu:
*Title:* Notification
*Values:* None, Daily, 2 Days, 3 Days, 4 Days, 5 Days, 6 Days, Weekly, Semimonthly, Monthly
Semimonthly occurs twice per month, such as on the 15th and final day of the month.
Monthly occurs once per month such as final day of the month.

EL:
*Title:* Ειδοποίηση
*Values:* Καμιά, Ημερήσια, 2 Ημέρες, 3 Ημέρες, 4 Ημέρες, 5 Ημέρες, 6 Ημέρες, 7 Ημέρες, Δεκαπενθήμερο, Μηνιαία

The email could leave early in the morning (04:00) or when the system has completed the calculations for the next day.
The default value of the dropdown menu should be set to: `None`, meaning that the email notifications tool will not send emails to the users, by default.

**Comment by nmalamos** [comment]
Weekly occurs once per week such as Monday.

**Comment by nmalamos** [comment]
I had this idea of a date picker, that the user will be able to select which days of the week (1-7) wishes to receive notifications, from Monday to Sunday.
Below the day picker, a drop-down menu with values: Weekly, Semimonthly, Monthly, will set the frequency of the e-mails.
@kickapoo , @aptiko is this more easy to implement?

**Comment by aptiko** [comment]
I agree to keep it as simple as possible. Having the options "daily", "every two days", ..., "monthly" is much simpler for the user, but it is complicated to implement. If the decision to send or not send an email is a function only of the date and the user's selection (i.e. it does not involve when the user was last emailed), things would be much simpler to implement.

An idea is this:

    Email me on  Monday, every X weeks
                 Tuesday
                 Wednesday
                 Thursday
                 Friday
                 Saturday
                 Sunday

where the days are a list box allowing multiple selection, by default with all days selected, and the "every X weeks" is greyed out unless only one day is selected on the list box.

On the other hand, this is much work on the user interface. If we keep the UI simple ("daily", "every two days", etc.) and instead add a `last_notified` field in the user profile table, and the email sending system consults and updates that field, it might be easier. Let kickapoo decide.

**Comment by aptiko** [comment]
@kickapoo, I need some help with this. I implemented (in my fork, aptiko/aira, branch issue_79) a management command:

    python manage.py send_notifications

which sends the emails. However, these emails are useless because the email always contains the message "You must irrigate" instead of something useful. Instead, it should contain, I guess, a list like this:

    Field XXX needs to be irrigated with YYY m².
    Field ZZZ needs to be irrigated with JJJ m².
    Field KKK does not need to be irrigated.

I think you will find the code I wrote easy to understand (and as always you can ask me questions), and it should be much easier for you to fix it than for me.

**Comment by nmalamos** [comment]
Considering this:
>it should contain, I guess, a list like this:
>Field XXX needs to be irrigated with YYY m².
>Field ZZZ needs to be irrigated with JJJ m².
>Field KKK does not need to be irrigated.

I remind that the idea was to present the `user` `home`, with links referring to the application itself.
So the content of the e-mail can be the  `user` `home` without the Openlayers map.

**Comment by nmalamos** [comment]
Also, I agree that the supervisor receives e-mails for the supervised account(s), but in different e-mails for each account.

**Comment by aptiko** [comment]
I hereby declare this issue as fixed. It's certainly not perfect, but that goes always. Any problems should be a new ticket.
