### ISSUE TITLE
Add CAPTCHA to `register` page

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#80]
A CAPTCHA feature should be added to `register` page.

I am not sure if it should be added in `login` page also, this is to be decided by you (@aptiko, @kickapoo ) based on your experience.

**Comment by aptiko** [comment]
Enhydris has this feature. You might want to copy stuff from there.

**Comment by kickapoo** [comment]
@aptiko , it will be nice if you can give me some pointers like file name,  lines, any kind of indicator...

**Comment by aptiko** [comment]
In the Enhydris directory, try `grep -r captcha *`. It will show you essentially all relevant locations in the code.

**Comment by kickapoo** [comment]
@aptiko , `grep` worked  like a charm. 
I see you used `django-simple-captcha`  for this but I have question related to django third party apps.
`aira` for registration uses a third party called `registration`. That's mean that i don't have a `registration/form.py` to implement `django-simple-captcha`  in my fields. 
Is there a way i could find this file and overwrite it? or i have to use an `ajax` solution with the addition of a button to our custom `app/templates/registration/` ? (http://django-simple-captcha.readthedocs.org/en/latest/usage.html#example-usage-for-ajax-form)

**Comment by aptiko** [comment]
Enhydris also uses `django-registration`. I don't remember the details clearly. Apparently it imports a form from `registration` and subclasses it in order to add the captcha. See `enhydris/urls.py` for how it is specified which form (sub)class is to be used.

**Comment by kickapoo** [comment]
@aptiko , @nmalamos  

Please tell if captcha is needed in the login form, from my point point of view is not needed.

**Comment by nmalamos** [comment]
Follow the Enhydris approach, as it is implemented at: http://openmeteo.org.
I agree that there is no need for captcha in the login form.
