### ISSUE TITLE
Account page groups

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#81]
`Account` page groups

From top to bottom following the position of appearing.

1st group:
Title: Update Profile / Ανανέωση Προφίλ
Contents: First name, Last name, Address

2nd group:
Title: Notification setup / Ρύθμιση Eιδοποιήσεων
Contents: Dropdown menu as #79 

3rd group:
Title: Supervision / Επίβλεψη
Contents:
1) An input of the supervisor username
2) In the case that the supervisor is set, the supervisor's username
3) In the case of a supervisor, a list of the supervised accounts

**Comment by kickapoo** [comment]
A sample of the menu:
![screenshot 2015-05-11 20 10 57](https://cloud.githubusercontent.com/assets/5064612/7570588/efe64352-f819-11e4-9dd4-440ef0cacea7.png)


@nmalamos, are you ok with the above layout of the form?  if yes, please close the issue

**Comment by nmalamos** [comment]
Please add a screenshot of mobile view. If it looks OK, it is fine for me.

**Comment by kickapoo** [comment]
![screenshot 2015-05-11 20 38 36](https://cloud.githubusercontent.com/assets/5064612/7571090/caf0b06a-f81d-11e4-8033-5e25f7661273.png)

**Comment by nmalamos** [comment]
It is ok.
Proceed.
