### ISSUE TITLE
In "advice" page the "Applied water" units (m³) are not in parenthesis (EN and EL)

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#83]
In `advice` page the "Applied water" units (in EN) are missing the parenthesis.
It should be like: (m³)
Same in EL, but an extra `(m3)` should be removed

**Comment by kickapoo** [comment]
We are aware of the translations problem (also mentioned in issue #84 ). Is something on server side.

Parenthesis will be fixed in other issues commits
