### ISSUE TITLE
In "advice" page the "Last recorded irrigation:" is not translated from EN to EL

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#84]
In `advice` page the "Last recorded irrigation:" is not translated from EN to EL, when switching languages from EN to EL

**Comment by kickapoo** [comment]
We are aware of the translations problem (also mentioned in issue #83). Is something on server side.

**Comment by kickapoo** [comment]
Global translations are fixed with aec0de01e69b1a851281ec1ebb37f23a46caca25 commit.
