### ISSUE TITLE
When supervisor goes to supervised "home" the phrase "Since the last recorded irrigation (../05/2015) up to ../05/2015, there is need of 0.00 mm additional water. " is missing

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#85]
When supervisor goes to supervised user `home`, the phrase:
*Since the last recorded irrigation (../05/2015) up to ../05/2015, there is need of 0.00 mm additional water.*
 is missing from **Irrigation Advice**

**Comment by kickapoo** [comment]
is it possible that the supervised user might not have any irrigation event stored to database ?

**Comment by nmalamos** [comment]
You are right.
That was what caused this.
I am closing this issue.
