### ISSUE TITLE
Add link to the IRMA Forum in the IRMA_SYS bar

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#87]
A link to the IRMA Forum in the IRMA_SYS bar should be added:
[Forum] (http://www.irrigation-management.eu/forumx/irrigation-system-gr)
on the right of `Try` without logging.
and on the right of: 
**Welcome:** `username`
if someone logs in.

**Comment by kickapoo** [comment]
This issue is referring to `aira-irma` templates.
