### ISSUE TITLE
When the supervisor presses the "Update" or "Back" button in "update_agrifield" returns to supervised user "home" instead of the supervisor account "home"

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#92]
When the supervisor presses the `Update` or `Back` button in `update_agrifield` returns to his `home` instead of the supervised account `home`.
The correct action should be to return to the supervised account `home`.

**Comment by kickapoo** [comment]
This is not user friendly logic. 
If you work in supervised user, you should always return to supervised list.
 
Consider the following situation: 
You updating something to supervised user Agrifield, this means that Advice will be affected. 
If the return is back to supervisor home, means that he need 2 clicks to see if the update was the one you needed - one to supervised user name to get the Agrifield list , second one to Advice.

**Comment by nmalamos** [comment]
We are saying the same thing.
I just set you as my supervisor. Please try to change something in one of my fields.
Once you press `Update` you will return to your `home`, not mine.

**Comment by kickapoo** [comment]
Ok, i changed the issue title.
