### ISSUE TITLE
Add "Irrigation Perfomance' button+graph for each field

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#96]
As stated in the relevant e-mail, an "Irrigation Perfomance' button+graph should be added for each field.
The user should choose `year`, `start_date` and `end_date`.
Also, the ability to export the graph data in csv or txt format should be included.

**Comment by kickapoo** [comment]
Please consider the finish up of issue with this commit kickapoo@5621d2e321a9ccb45b98a900af74ab1d25453506.
