### ISSUE TITLE
Impose 24 h offset to daily aggregated timeseries for maps use

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#98]
Up to now, daily aggregated timeseries had a timestamp of 00:00, `next day`.
In order to present the daily aggregated timeseries for the correct day, a 24 h offset could be imposed in order to show maps with correct date.

**Comment by kickapoo** [comment]
`DayBeforeYesterday` solution states that: Show user `DayBeforeYesterday` but fetch `Yesterday` data. 

Also, with dea777e commit there is a debugging console log statement. If you are absolute sure that in the future you will always remember about `DayBeforeYesterday` , I will remove it.

**Comment by nmalamos** [comment]
I am sure that we will forget about it, so leave it.
